name: Release
on: workflow_dispatch

jobs:
  Publish:
    name: Publish and Release on Node ${{ matrix.node }} and ${{ matrix.os }}

    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Run semantic-release command
        run: yarn semantic-release

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
